FROM hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/sl-pyt:0.3.0

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get -y install python3-opencv
RUN pip install opencv-python ipywidgets xlrd openpyxl
